#!/usr/bin/env bash

# re-exec under bash if running as sh
if [ -z "${BASH_VERSION:-}" ]; then
    exec bash "$0" "$@"
fi

source lib-utils

need() { has "$1" || printf 'autostart: missing %s\n' "$1" >&2; }

need dbus-update-activation-environment
need shikane
need pipewire
need swayidle
need swww-daemon
need waybar
need mako
need lxqt-policykit-agent

# labwc-daemons &
dbus-update-activation-environment --all

has shikane && shikane &
has pipewire && pipewire &

has swayidle && swayidle -w &
has swww-daemon && swww-daemon --format xrgb &  # Wallpapers
has waybar && waybar &
has mako && mako &  # Notifications

has lxqt-policykit-agent && lxqt-policykit-agent &
has poweralertd && poweralertd &
