#!/usr/bin/env sh

#
# Environment settings
#

# Defaults
export TERMINAL="${TERMINAL:-foot}"
export BROWSER="${BROWSER:-firefox-wayland}"
export EDITOR="${EDITOR:-hx}"
export READER="${READER:-sioyek}"
export VIEWER="${VIEWER:-nsxiv}"

export TMUX_TMPDIR="${TMUX_TMPDIR:-${XDG_RUNTIME_DIR:-/tmp}}"

# XDG User Directories
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_BIN_HOME="${XDG_BIN_HOME:-$HOME/.local/bin}"
export XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
export XDG_DATA_DIRS="${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"

export XDG_PUBLICSHARE_DIR="${HOME}"
export XDG_TEMPLATES_DIR="${HOME}"
export XDG_DESKTOP_DIR="${HOME}/desktop"
export XDG_DOCUMENTS_DIR="${HOME}/docs"
export XDG_DOWNLOAD_DIR="${HOME}/downloads"
export XDG_MUSIC_DIR="${HOME}/music"
export XDG_PICTURES_DIR="${HOME}/pictures"
export XDG_VIDEOS_DIR="${HOME}/videos"

export DIR_MEDIA="${DIR_MEDIA:-$HOME/media}"
export DIR_MUSIC="${DIR_MUSIC:-$XDG_MUSIC_DIR}"
export DIR_WALLPAPERS="${DIR_WALLPAPERS:-$HOME/wallpapers}"
export DIR_NOTES="${DIR_NOTES:-$HOME/notes}"
export DIR_STICKERS="${DIR_STICKERS:-$HOME/stickers}"

export TODO="${TODO:-$DIR_NOTES/todo}"

# Program Directories
export CARGO_HOME="${CARGO_HOME:-$XDG_DATA_HOME/cargo}"
export RUSTUP_HOME="${RUSTUP_HOME:-$XDG_DATA_HOME/rustup}"
export GOPATH="${GOPATH:-$XDG_DATA_HOME/go}"
export GNUPGHOME="${GNUPGHOME:-$XDG_DATA_HOME/gnupg}"
export WGETRC="${WGETRC:-$XDG_CONFIG_HOME/wget/wgetrc}"
export PYTHONSTARTUP="${PYTHONSTARTUP:-$XDG_CONFIG_HOME/python/pythonrc}"
export PYTHON_HISTORY="${PYTHON_HISTORY:-$XDG_STATE_HOME/python/history}"
export NODE_REPL_HISTORY="${NODE_REPL_HISTORY:-$XDG_STATE_HOME/node/history}"
export npm_config_cache="${npm_config_cache:-$XDG_CACHE_HOME/npm}"
export NPM_CONFIG_USERCONFIG="${NPM_CONFIG_USERCONFIG:-$XDG_CONFIG_HOME/npm/npmrc}"
export PERF_CONFIG="${PERF_CONFIG:-$XDG_CONFIG_HOME/perf/perfconfig}"

case ":${PATH}:" in
	*":${XDG_BIN_HOME}:"*) ;;
	*) export PATH="${XDG_BIN_HOME}:${PATH}" ;;
esac

### PROGRAM SETTINGS ###
export KPXC_CONFIG_LOCAL="${KPXC_CONFIG_LOCAL:-$XDG_STATE_HOME/keepassxc/keepassxc.ini}"

# Password Manager
export PASH_LENGTH="${PASH_LENGTH:-50}"
export PASH_PATTERN="${PASH_PATTERN:-_[:alnum:][:graph:]}"
export PASH_KEYID="${PASH_KEYID:-jackojc@gmail.com}"
export PASH_DIR="${PASH_DIR:-$XDG_DATA_HOME/passwords}"
export PASH_CLIP="${PASH_CLIP:-wl-copy}"
export PASH_TIMEOUT="${PASH_TIMEOUT:-6}"

# Man Settings
export MANROFFOPT='-c'
export PAGER='less'
export MANPAGER="tool-batpager"

# AWWW (wallpapers)
export AWWW_TRANSITION="any"
export AWWW_TRANSITION_FPS="60"
export AWWW_TRANSITION_STEP="90"
export AWWW_TRANSITION_DURATION="1"
