# Theme: Blindboy
# Author: Jackojc

# Based on Okabe & Ito colours
# https://jfly.uni-koeln.de/color/#pallet

# Notes:
# - Use warm and cool colours alternatively
# - When using two warm or cool colours, use
#   distinct brightness or saturation
# - Avoid combinations of low saturation or low brightness

# Syntax
"comment" = { fg = "white_bright", bg = "background_bright" }

"function" = { fg = "orange_bright", modifiers = ["bold"] }
"constructor" = "orange_bright"

"type" = { fg = "cyan_bright", modifiers = ["italic"] }
"namespace" = "cyan_bright"

"string" = "yellow_bright"
"special" = { fg = "yellow_bright", modifiers = ["bold"] }

"keyword" = "blue_bright"
"label" = "blue_bright"
"attributes" = "blue_bright"

"variable" = "white"
"variable.other.member" = "white"
"constant" = "white"
"operator" = "dim"
"punctuation" = "dim"

"diff.plus" = "added"
"diff.minus" = "removed"
"diff.delta" = "changed"

"debug" = "dim"
"hint" = "dim"
"info" = "cyan_bright"
"warning" = "orange_bright"
"error" = { fg = "vermillion_bright", modifiers = ["bold"] }

# Markup
"markup.heading" = { fg = "white_bright", modifiers = ["bold"] }

"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }

"markup.link.text" = "cyan_bright"
"markup.link.url" = { fg = "dim", modifiers = ["underlined"] }

"markup.list" = "orange_bright"
"markup.quote" = "dim"
"markup.raw" = "yellow_bright"

# Diagnostic
"diagnostic" = { modifiers = ["underlined"] }

"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diagnostic.error" = { underline = { style = "curl" } }

# UI
"ui.background" = { bg = "background" }
"ui.window" = { bg = "structure" }
"ui.gutter" = { bg = "background" }

"ui.popup" = { bg = "navy" }
"ui.menu" = { bg = "navy" }
"ui.statusline" = { bg = "navy" }
"ui.help" = { bg = "navy" }

"ui.text" = "white_bright"
"ui.text.focus" = "white_bright"

"ui.selection" = { bg = "blue", fg = "cyan" }
"ui.selection.primary" = { bg = "cyan", fg = "white_bright" }

"ui.cursor" = { bg = "orange_bright" }

"ui.cursor.primary.normal" = { fg = "yellow_bright", modifiers = ["reversed"] }
"ui.cursor.primary.insert" = { fg = "green_bright", modifiers = ["bold", "reversed"] }
"ui.cursor.primary.select" = { fg = "blue_bright", modifiers = ["reversed"] }

"ui.cursorline.primary" = { fg = "yellow", bg = "navy" }
"ui.cursor.match" = { fg = "vermillion", modifiers = ["reversed"] }

"ui.linenr" = { fg = "structure" }
"ui.linenr.selected" = { fg = "dim", modifiers = ["bold"] }

"ui.bufferline" = { bg = "black", fg = "white" }
"ui.bufferline.active" = { bg = "navy_bright", fg = "white_bright" }

"ui.menu.scroll" = { fg = "white", bg = "navy_bright" }
"ui.menu.selected" = { fg = "yellow", modifiers = ["reversed"] }

"ui.statusline.inactive" = { bg = "navy_bright", fg = "dim" }
"ui.statusline.insert" = { bg = "orange", fg = "black", modifiers = ["bold"] }
"ui.statusline.normal" = { bg = "cyan_bright", fg = "black" }
"ui.statusline.select" = { bg = "blue", fg = "white_bright", modifiers = ["italic"] }

"ui.virtual.inlay-hint" = { fg = "dim", modifiers = ["italic"] }
"ui.virtual.whitespace" = { fg = "guide" }
"ui.virtual.indent-guide" = { fg = "guide" }
"ui.virtual.ruler" = { bg = "navy" }
"ui.virtual.jump-label" = { fg = "yellow_bright", modifiers = ["bold", "underlined"] }


[palette]
background        = "#0e0f1a"
foreground        = "#f4f4f4"
background_bright = "#171824"
foreground_bright = "#ffffff"
white             = "#f4f4f4"
black             = "#000000"
white_bright      = "#ffffff"
black_bright      = "#8a8578"
dim               = "#8a8578"
structure         = "#59564e"
guide             = "#292a34"
orange            = "#e69f00"
yellow            = "#f0e442"
vermillion        = "#d55e00"
purple            = "#cc79a7"
blue              = "#2981c2"
navy              = "#1f202a"
cyan              = "#56b4e9"
green             = "#009e73"
orange_bright     = "#f4aa24"
yellow_bright     = "#fdf153"
vermillion_bright = "#e3691d"
purple_bright     = "#e187b9"
blue_bright       = "#2f89cb"
navy_bright       = "#292a34"
cyan_bright       = "#63c0f7"
green_bright      = "#23ab80"

added             = "#56b4e9"
changed           = "#f0e442"
removed           = "#e69f00"
error             = "#d55e00"
warning           = "#e69f00"
success           = "#56b4e9"
info              = "#2981c2"
