# Potentially can fuck up tmux
# term=screen-256color

# app-id=terminal
# title=terminal

initial-window-size-chars=80x25

# Terminus as fallback. There was an issue with falling back to
# Nimbus Sans and some glyphs not rendering at the right width.
font=Intel One Mono:size=12, Terminus (TTF):size=12
font-size-adjustment=1

box-drawings-uses-font-glyphs=no
dpi-aware=yes

pad=0x0 center
resize-by-cells=no
resize-delay-ms=0
bold-text-in-bright=no

word-delimiters=,│`|:"'()[]{}<>-_
selection-target=both

[url]
osc8-underline=always

[key-bindings]
scrollback-up-page=Shift+Page_Up
scrollback-down-page=Shift+Page_Down

clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste
primary-paste=none

search-start=none

font-increase=Control+plus Control+equal Control+KP_Add
font-decrease=Control+minus Control+KP_Subtract
font-reset=Control+0 Control+KP_0

spawn-terminal=none
show-urls-launch=Control+Shift+o
show-urls-copy=none

[mouse-bindings]
scrollback-up-mouse=BTN_WHEEL_BACK
scrollback-down-mouse=BTN_WHEEL_FORWARD

font-increase=none
font-decrease=none

selection-override-modifiers=Shift
primary-paste=BTN_MIDDLE
select-begin=BTN_LEFT
select-begin-block=Control+BTN_LEFT
select-extend=BTN_RIGHT
select-extend-character-wise=Control+BTN_RIGHT
select-word=BTN_LEFT-2
select-word-whitespace=Control+BTN_LEFT-2

[colors-dark]
alpha=0.9961

background=0e0f1a
foreground=f4f4f4

regular0=000000   # black
regular1=d55e00   # vermillion
regular2=009e73   # bluish_green
regular3=f0e442   # yellow
regular4=2981c2   # blue_readable
regular5=cc79a7   # reddish_purple
regular6=56b4e9   # sky_blue
regular7=f4f4f4   # foreground

bright0=8a8578    # dim
bright1=e3691d    # bright_vermillion
bright2=23ab80    # bright_bluish_green
bright3=fdf153    # bright_yellow
bright4=2f89cb    # bright_blue
bright5=e187b9    # bright_reddish_purple
bright6=63c0f7    # bright_sky_blue
bright7=ffffff    # foreground_bright

urls=fdf153   # bright yellow
