theme = "ayu_dark"

[editor]
line-number = "relative"
bufferline = "multiple"  # show tabs when muliple buffers
end-of-line-diagnostics = "disable"

text-width = 120
rulers = [80, 120]
cursorline = true

scrolloff = 3
scroll-lines = 1

color-modes = true  # mode indicator changes colour
true-color = true  # terminal features

completion-replace = true
preview-completion-insert = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.characters]
newline = "¬"

[editor.whitespace.render]
newline = "all"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[editor.lsp]
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.search]
smart-case = false

[editor.statusline]
left = ["selections", "mode", "spacer", "file-modification-indicator", "read-only-indicator", "spinner"]
center = ["file-name", "read-only-indicator"]
right = ["diagnostics", "file-type", "separator", "position", "position-percentage", "spacer"]

mode.normal = "normal"
mode.insert = "insert"
mode.select = "select"

[keys.normal."space"]  # Usermode
x = ":buffer-close"

[keys.insert]
S-tab = "move_parent_node_start"

# Half page movement is better
pageup = "half_page_up"
pagedown = "half_page_down"

# Better selections with movement keys
"S-up" = "extend_line_up"
"S-down" = "extend_line_down"
"S-left" = "extend_char_left"
"S-right" = "extend_char_right"

"S-home" = "extend_to_line_start"
"S-end" = "extend_to_line_end"

# ctrl-left/right to jump around words in insert mode
"C-left" = ["move_prev_long_word_start", "collapse_selection"]
"C-right" = ["move_next_long_word_end", "move_char_right", "collapse_selection"]

[keys.normal]
# Switch buffers
tab = ":bn"
S-tab = ":bp"

# [[ and ]] move between nodes
"]" = { "]" = "move_parent_node_end" }
"[" = { "[" = "move_parent_node_start" }

# Swap b and q
b = "replay_macro"
B = "record_macro"

q = "move_prev_word_start"
Q = "move_prev_long_word_start"

w = "move_next_word_end"
W = "move_next_long_word_end"

# Misc
X = "extend_line_above"
"#" = "toggle_comments"

# Collapse multiple selections and shrink primary
esc = ["normal_mode", "collapse_selection", "keep_primary_selection"]

# Half page movement is better
pageup = "half_page_up"
pagedown = "half_page_down"

# Better selections with movement keys
"S-left" = "extend_char_left"
"S-right" = "extend_char_right"
"S-up" = "extend_line_up"
"S-down" = "extend_line_down"
"S-home" = "extend_to_line_start"
"S-end" = "extend_to_line_end"

"C-s" = "surround_add"

# Jump between splits
"C-up" = "jump_view_up"
"C-down" = "jump_view_down"
"C-left" = "jump_view_left"
"C-right" = "jump_view_right"

[keys.select]
# Unbind b in this context because usually we use 'w' and 'q'
b = "no_op"
B = "no_op"

q = "extend_prev_word_start"
Q = "extend_prev_long_word_start"

w = "extend_next_word_end"
W = "extend_next_long_word_end"

# [[ and ]] move between nodes
"[" = { "[" = "select_prev_sibling" }
"]" = { "]" = "select_next_sibling" }

# Half page movement is better
pageup = "half_page_up"
pagedown = "half_page_down"
